### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by izaakrogan** [olgnaydn/R#1]
Hi, sorry for this but I'm having trouble connecting to my Heroky postgreSQL database, which is hosted on amazon.

I followed your connection.R file exactly, filling in the dbname, host, user and password but getting error:

`
Error in postgresqlNewConnection(drv, ...) :
  RS-DBI driver: (could not connect xxxxx@xxxxxx.eu-west-1.rds.amazonaws.com on dbname "xxxxx"
)
`

Any idea what I might be doing wrong?

**Comment by olgnaydn** [comment]
Hi, 

Thank you for your question. 

Have you called driver by this script  `drv <- dbDriver("PostgreSQL")` 
And have you put the host, port, username, pass with proper syntax.

Please feel free to contact with me any further questions.

**Comment by izaakrogan** [comment]
Thanks for getting back to me!

Solved it in the end. The problem was that my database contained jsonb fields and rpostgresql didn't like it. I changed to DBI and it works fine.

`
library(DBI)
con <- dbConnect(
    RPostgres::Postgres(),
    dbname='XXX',
    host='XXX',
    user='XXXX',
    password='XXXX'
)
`
Thanks again 👍

**Comment by olgnaydn** [comment]
Your welcome Izaak..

Yesss. Json parts aren't good for RPostgresql :)

I'm very happy that you have solved it..

Have a nice day with R..

Best..

---

Olgun AYDIN

Statistician, M.Sc., Candidate of Ph.D
